[WIP] docs: add license and readme
bjohansebas/codemod pull request #13
Opened 2024-11-07 22:32 UTC by bjohansebas

The necessary documentation is added to be moved to the Express organization

closes #12

2024-11-07 22:34 UTC, bjohansebas commented on LICENSE
> +Copyright (c) 2024 Filip Kudla <kjugi@users.noreply.github.com>
@kjugi change the email if you want

2024-11-09 23:56 UTC, kjugi commented on LICENSE
> +Copyright (c) 2024 Filip Kudla <kjugi@users.noreply.github.com>
done, thanks for ping 👍

2024-11-11 02:40 UTC, bjohansebas commented
I added a workflow to automate the use of the package, so it stays updated after each PR. It will be useful when others want to add more options but don't update the README

2024-11-11 23:39 UTC, bjohansebas commented on README.md
> +[![OpenSSF Scorecard Badge][ossf-scorecard-badge]][ossf-scorecard-visualizer]
This will not display correctly yet, but once it's published and moved to Express, it will be displayed properly.

2024-11-11 23:48 UTC, bjohansebas commented
@kjugi If you think the texts can be improved, feel free to change them

2024-11-11 23:59 UTC, kjugi requested changes
small comments

2024-11-11 23:59 UTC, bjohansebas commented on .github/workflows/generate-readme.yml
> +        run: node ./generate-help-docs.mjs
good idea

2024-11-12 00:12 UTC, bjohansebas commented on .github/workflows/generate-readme.yml
> +            title: 'Update options in README'
I suppose the change I made is enough, right?

2024-11-12 00:18 UTC, bjohansebas commented on .github/actions/generate-help-docs.mjs
> +
It's a small script, I don't see the need to do this check

2024-11-14 23:49 UTC, kjugi commented on .github/workflows/generate-readme.yml
> +            title: 'Update options in README'
I'm fine when PR is created only when we change file from list 👌🏻

2024-11-14 23:53 UTC, bjohansebas commented on .github/workflows/generate-readme.yml
> +            title: 'Update options in README'
In fact, it works that way now, when something in `index.ts` is changed, the workflow will run, and if that change affects the output, a PR will be opened.

2024-11-15 00:03 UTC, kjugi approved these changes

2024-11-15 00:14 UTC, merged

2024-11-15 00:19 UTC, bjohansebas commented
@kjugi I'm going to send the request to move this repository to Express.